trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:

# =========================
# CI - Restore
# =========================

- task: DotNetCoreCLI@2
  displayName: 'Restore'
  inputs:
    command: 'restore'
    projects: '**/*.csproj'


# =========================
# CI - Build
# =========================

- task: DotNetCoreCLI@2
  displayName: 'Build'
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration) --no-restore'


# =========================
# CI - Test
# =========================

- task: DotNetCoreCLI@2
  displayName: 'Test'
  inputs:
    command: 'test'
    projects: '**/*Tests/*.csproj'
    arguments: '--configuration $(buildConfiguration) --no-build'


# =========================
# EF Core - Install Tool
# =========================

- task: Bash@3
  displayName: 'Install EF Core Tool'
  inputs:
    targetType: 'inline'
    script: |
      dotnet tool install --global dotnet-ef
      echo '##vso[task.prependpath]$HOME/.dotnet/tools'


# =========================
# EF Core - Apply Migration
# =========================

- task: Bash@3
  displayName: 'Apply EF Core Migrations'
  inputs:
    targetType: 'inline'
    script: |
      dotnet ef database update --connection "$(AZURE_SQL_CONNECTION_STRING)"


# =========================
# CI - Publish
# =========================

- task: DotNetCoreCLI@2
  displayName: 'Publish'
  inputs:
    command: 'publish'
    publishWebProjects: true
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/publish'
    zipAfterPublish: true


# =========================
# CD - Deploy to Azure App Service
# =========================

- task: AzureRmWebAppDeployment@4
  displayName: 'Deploy to Azure App Service'
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'DevopsConnection'
    appType: 'webAppLinux'
    WebAppName: 'first-app-azure'
    packageForLinux: '$(Build.ArtifactStagingDirectory)/**/*.zip'