trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:

# =========================
# Restore
# =========================

- task: DotNetCoreCLI@2
  displayName: 'Restore'
  inputs:
    command: 'restore'
    projects: '**/*.csproj'


# =========================
# Build
# =========================

- task: DotNetCoreCLI@2
  displayName: 'Build'
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration) --no-restore'


# =========================
# Test
# =========================

- task: DotNetCoreCLI@2
  displayName: 'Test'
  inputs:
    command: 'test'
    projects: '**/*Tests/*.csproj'
    arguments: '--configuration $(buildConfiguration) --no-build'


# =========================
# Install EF Core
# =========================

- task: Bash@3
  displayName: 'Install EF Core Tool'
  inputs:
    targetType: 'inline'
    script: |
      dotnet tool install --global dotnet-ef
      echo "##vso[task.prependpath]$HOME/.dotnet/tools"


# =========================
# Apply EF Core Migration
# =========================

- task: Bash@3
  displayName: 'Apply EF Core Migrations'
  inputs:
    targetType: 'inline'
    workingDirectory: '$(Build.SourcesDirectory)'
    script: |
      dotnet ef database update \
        --project "$(Build.SourcesDirectory)/dotNetProject/dotNetProject.csproj" \
        --startup-project "$(Build.SourcesDirectory)/dotNetProject/dotNetProject.csproj" \
        --connection "$AZURE_SQL_CONNECTION_STRING"
  env:
    AZURE_SQL_CONNECTION_STRING: $(AZURE_SQL_CONNECTION_STRING)


# =========================
# Publish
# =========================

- task: DotNetCoreCLI@2
  displayName: 'Publish'
  inputs:
    command: 'publish'
    publishWebProjects: true
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/publish'
    zipAfterPublish: true


# =========================
# Deploy
# =========================

- task: AzureRmWebAppDeployment@4
  displayName: 'Deploy to Azure App Service'
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'DevopsConnection'
    appType: 'webAppLinux'
    WebAppName: 'first-app-azure'
    packageForLinux: '$(Build.ArtifactStagingDirectory)/**/*.zip'